title: 2019312219_Yanghyeondong
iconURL: assets/default-icon.png
theme: jekyll-theme-leaf

baseurl:

remote_theme: SupunKavinda/jekyll-theme-leaf

# for a clean URL
permalink: :slug

social:
  twitter: _SupunKavinda
  github: SupunKavinda

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
google_analytics: UA-NNNNNNNN-N
