title: 2019312219 양현동 OSS
iconURL: assets/default-icon.png
theme: jekyll-theme-leaf

baseurl:

remote_theme: SupunKavinda/jekyll-theme-leaf

# for a clean URL
permalink: :slug

social:
  twitter: 
  github:

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
google_analytics: UA-NNNNNNNN-N
